name: Check pod status

on:
  push:
    branches:
      - master

jobs:
  Check_pod_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checking the repository
        uses: actions/checkout@v4
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n  StrictHostKeyChecking no" > ~/.ssh/config
      - name: Connect SSH and check pod status
        id: pod_status
        run: |
          ssh ${{ secrets.K8S_USER }}@${{ secrets.K8S_HOST }} -o ProxyCommand="ssh -W %h:%p -q ${{ secrets.PROXY_USER }}@${{ secrets.PROXY_HOST }} -p ${{ secrets.PROXY_PORT }}" \
          "kubectl get pods -A --field-selector status.phase!=Running,status.phase!=Succeeded"
